### ISSUE TITLE
Add support for rolling functions

### ISSUE THREAD

**Issue by zsz00** [JuliaML/TableTransforms.jl#121]
Hope support Roll a function over data, run a statistic along a [weighted] data window 

ref:  https://github.com/JeffreySarnoff/RollingFunctions.jl

**Comment by JeffreySarnoff** [comment]
as with https://github.com/JuliaData/DataFrames.jl/issues/3163
What do you need that is missing from RollingFunctions?

**Comment by zsz00** [comment]
yes, I have time series columns  need roll process. 
1. I hope more integration with TableTransforms.jl or dataframes.jl. or more using doc. 
2. need rolling(function, data, windowsize, stride)
3. RollingFunctions.jl newest version realse in 2019.3, I mistook it for a lack of active development.

**Comment by JeffreySarnoff** [comment]
RollingFunctions.jl has been stable for that long.
There are some innovations that I am considering -- none would be necessary
for most uses, though some may be welcome.
The upgrade, if any, is not next month.

**Comment by juliohm** [comment]
@JeffreySarnoff in you case you want to integrate with the TableTransforms.jl API, all you need to do is implement the function `applyfeat`, and if the transform `isrevertible`, you can also implement `revertfeat`. So you can do the following in your RollingFunctions.jl package:

```julia
import TableTransforms: applyfeat, revertfeat

# optionally define some pre-processing step
import TableTransforms: preprocessing

function preprocess(transform::MyRollingTransform, table)
  # do some preprocessing on the table
  "preprocessed object"
end

function applyfeat(transform::MyRollingTransform, table, prep)
  # do something with cols of table
  cols = Tables.columns(table)

  # materialize the result into the original table type
  result = map(roll, cols)

  # cache in case we need to revert transform
  cache = nothing

  # return result and cache
  result, cache
end
```

If you rolling functions operate on each column individually, then you can do something even simpler. Take a look at our Colwise transforms, for example: https://github.com/JuliaML/TableTransforms.jl/blob/master/src/transforms/center.jl

This is all you need to get these column-based transforms run in parallel with Transducers.jl

**Comment by JeffreySarnoff** [comment]
thank you

**Comment by juliohm** [comment]
I will close this issue as no one is working actively on it.

**Comment by JeffreySarnoff** [comment]
@juliohm reopen it -- I have been rearchitecting RollingFunctions.jl, in part to allow interoperability simply and both as client and as servicer.   I am glad you posted, and this is now part of the direction -- not there yet, however each such request/suggestion better shapes the way of it.

**Comment by juliohm** [comment]
@JeffreySarnoff I am reopening it assuming that something will be implemented either here or in RollingFunctions.jl to allow support for rolling function transforms.

**Comment by juliohm** [comment]
I am closing this issue again, we can re-open whenever we initiate developments related to TableTransforms.jl
