### ISSUE TITLE
Fix documentation and build in the master branch

### ISSUE THREAD

**Issue by juliohm** [JuliaML/TableTransforms.jl#169]
The main page of the documentation is missing some plots and the tests are failing on master due to updates in Plots.jl version probably.

**Comment by wasup-yash** [comment]
Hey do we need to Document [https://juliaml.github.io/TableTransforms.jl/stable/](url) as a readme file in the project? as I am new to the project can you reference the resources what i need to understand in order to work on this issue

**Comment by juliohm** [comment]
I don't know if I understood your question. We just need to fix the documentation build and the tests that are failing currently.

**Comment by wasup-yash** [comment]
> I don't know if I understood your question. We just need to fix the documentation build and the tests that are failing currently.

oh, now it's clear to me what the actual issue demands, thanks for explaining it to me.

**Comment by juliohm** [comment]
The issue has been fixed by @eliascarv. The build is failing on Julia v1.6 due to a bug in Julia itself.
