### ISSUE TITLE
DropExtrema

### ISSUE THREAD

**Issue by juliohm** [JuliaML/TableTransforms.jl#193]
The `DropExtrema(low=0.01, high=0.99)` transform drops extreme values in both lower and upper tails.

**Comment by Jay-sanjay** [comment]
sir , where is the function DropExtrema defined I am not getting it in the TableTransform.jl

**Comment by juliohm** [comment]
The issue is about adding the transform, it doesn't exist yet.

Em sex., 8 de set. de 2023 04:26, Jay-sanjay ***@***.***>
escreveu:

**Comment by juliohm** [comment]
The `DropExtrema` transform is a transform that computes `a = quantile(column, low)` and `b = quantile(column, high)`, and then discards all rows for which the values of the `column` lie outside the interval `[a,b]`.

**Comment by Jay-sanjay** [comment]
Sir , this is the link for the PR
https://github.com/JuliaML/TableTransforms.jl/pull/197

**Comment by juliohm** [comment]
Fixed in the master branch.
