### ISSUE TITLE
Coerce fails with string colspec

### ISSUE THREAD

**Issue by juliohm** [JuliaML/TableTransforms.jl#194]
Currently we can `Coerce(:a => Multiclass)`, but we can't `Coerce("a" => Multiclass)`.

**Comment by Jay-sanjay** [comment]
Hello sir, I guess the above issue could be fixed just by adding a similar line like this
https://github.com/JuliaML/TableTransforms.jl/blob/47db7ce725b47d2df0f010a4c31d5c5eb6cf454c/src/transforms/coerce.jl#L25
for defining a string , what do you think sir.

**Comment by Jay-sanjay** [comment]
I can just raise a PR on it

**Comment by juliohm** [comment]
Thank you @Jay-sanjay for considering a PR.

Please try to follow the convention in other transforms that already use the `ColSpec`.

**Comment by Jay-sanjay** [comment]
sir here is the link to the PR
https://github.com/JuliaML/TableTransforms.jl/pull/196
