### ISSUE TITLE
Map accepting row functions

### ISSUE THREAD

**Issue by davibarreira** [JuliaML/TableTransforms.jl#290]
It seems that the `Map` transform does not accept row functions, for example:
```julia
Map(row->row.a + row.b => :NewColumnName)
Map(row->sum(row) => :NewColumnName)
```
Is this by design? I've taken a look at the implementation of how `Map` is applied, and I noticed that the data is first transformed into column form, and then a generator is produced. Isn't the `Map` transform always applied row-wise? Is there a reason to parsing the table column-wise instead?

Using the `ColumnSelectors.AllSelector` type, one can place an `if` and apply the function row-wise, without modifying much of the current implementation. But this is not a perfect solution, as it produces errors if the user actually pass an AllSelector and writes the function with `(a,b,c,d)` containing all columns.

**Comment by juliohm** [comment]
Good question. We are effectively mapping a function to all rows of the table, so we could potentially consider the proposed syntax. However, not all `row` objects support the syntax `row.a` so we need to make sure that the table type is wrapped into a new table type with this guarantee.

@eliascarv do you have any comment regarding this proposal? At a quick glance, it can drastically simplify the `Map` syntax.

**Comment by eliascarv** [comment]
@davibarreira, after discussion, perhaps the best decision would be to change the current syntax to this:
```julia
Map(fun, ...)
Map(fun => target, ....)
```
Where `fun` is a function that receives a `row` and returns a value: `fun(row) -> value`.

For example, the following code:
```julia
Map(:a => sin, "b" => cos => :cos_b)
```
Would be written like this:
```julia
Map((row -> sin(row.a)), (row -> cos(row.b)) => :cos_b)
```
Can you do a PR to investigate this please?

**Comment by juliohm** [comment]
To clarify, this PR would be investigative. We can compare the pros and cons of the two approaches and decide later if the breaking change is worth.

**Comment by davibarreira** [comment]
I've implemented the solution I mentioned and submitted the PR. You guys can check if you think it properly addresses the issue, or if it is better to keep as it is now.

**Comment by juliohm** [comment]
Thank you @davibarreira for experimenting with this idea. Closing the issue.
