### ISSUE TITLE
Please move colspec.jl to the root folder

### ISSUE THREAD

**Issue by juliohm** [JuliaML/TableTransforms.jl#36]
I noticed that you added colspec.jl to the transforms folder, but it is not a transform @eliascarv. Can you please move it to the root folder and update the include?

**Comment by eliascarv** [comment]
OK, I will do it

**Comment by juliohm** [comment]
@eliascarv appreciate if you can take a look at this now that we merged the PR you were working on. 💯

**Comment by eliascarv** [comment]
OK, I will do it now!

**Comment by juliohm** [comment]
This issue is now fixed. I think we also need to rename _filter to a public function name to be used by other transforms. I will open a separate issue for that.
