### ISSUE TITLE
Add documentation with Documenter.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaML/TableTransforms.jl#43]
The project has grown a lot with the latest additions by @eliascarv and @ceferisbarov ❤️ I think it is time to add a documentation page with Documenter.jl.

In my opinion an ideal documentation for this package would consist of two pages:

1. A page with the examples from the README and other examples showing revertibility of pipelines.
2. A page with a list of docstrings for all available transforms and an index table (or side page) that users could click to jump directly to any transform's docstring.

We can then focus on writing very good docstrings and never bother again about updating the documentation. Any newly added transform could just be appended to the docstring page.

**Comment by ceferisbarov** [comment]
I would like to learn `Documenter.jl` and work on this issue, if it is not very urgent.

**Comment by juliohm** [comment]
Hi @ceferisbarov it would be nice if you could align with @eliascarv to review all docstrings systematically before the Documenter.jl part. We have a roadmap that consists of:

1. Reviewing all docstrings of all transforms to improve clarity and short examples when that is possible.
2. Creating the documentation page with Documenter.jl with the two pages described above.

Feel free to coordinate between each other a subset of docstrings to review. We could then review multiple PRs in paralell. That would be great.

**Comment by eliascarv** [comment]
List of docstrings that should be improved:
[] `Select` 
[] `Reject` 
[] `Filter`
[] `DropMissing`
[] `Rename` 
[] `Replace` 
[] `Coalesce` 
[] `Coerce`
[] `Identity`
[] `Center`
[] `Scale` 
[] `MinMax`
[] `Interquartile`
[] `ZScore`
[] `Quantile`
[] `Functional`
[] `EigenAnalysis` / `PCA` / `DRS` / `SDS`
[] `Sequential` 
[] `Parallel`

**Comment by eliascarv** [comment]
@ceferisbarov we'll share this work between us. Each PR must update 5 docstrings.

**Comment by ceferisbarov** [comment]
Okay. Which ones am I working on now?

**Comment by eliascarv** [comment]
> List of docstrings that should be improved:
> 
> @eliascarv:
> 
>  ...

Here I have separated the docstrings into groups of 5 and assigned each one to one of us.

**Comment by ceferisbarov** [comment]
Sorry, I was watching it directly from the mail, so I didn't see them.

**Comment by eliascarv** [comment]
No problems

**Comment by juliohm** [comment]
We finished two batches of updates. Only two more to go.

**Comment by juliohm** [comment]
Awesome progress, now we just miss the final batch of transforms before adding all of them to the Documenter.jl page. Do you think you can work on that @ceferisbarov ?

**Comment by ceferisbarov** [comment]
@juliohm  Yes, I opened a PR.

**Comment by juliohm** [comment]
Thank you! Now we can proceed and add a page to the documentation with all transforms listed in a @docs block. @eliascarv can you work on that? We have examples in Meshes.jl and GeoStats.jl of such blocks. We can call this page the reference guide.

**Comment by juliohm** [comment]
Awesome work!
