### ISSUE TITLE
Introduce RowTable and ColTable transforms

### ISSUE THREAD

**Issue by ablaom** [JuliaML/TableTransforms.jl#62]
For row table inputs, will the output of a transform necessarily have `rowaccess`?  Is there a general principle guiding the form of the output in general? Can I arrange that the ouput is `Tables.materialize`d? 

In MLJ  we generally `materialize` based on input type, but is has been argued that an option to specify the output type would be useful. I'm wondering what the authors of  TableTransforms.jl think about such questions.

**Comment by juliohm** [comment]
This is a good question. We currently materialize the same type of the
input assuming that users chosen that type for a reason. We could even
introduce transforms that just change the representation to row or column.
I think it addresses two cases.

Em qui., 28 de abr. de 2022 19:28, Anthony Blaom, PhD <
***@***.***> escreveu:

**Comment by juliohm** [comment]
@ceferisbarov would you like to git this issue a try? Basically, we need two structs RowTable and ColTable that apply the function Tables.rowtable and Tables.columntable lazily in pipelines. For example, something like:

```julia
struct RowTable end

apply(::RowTable, table) = Tables.rowtable(table), table
revert(::RowTable, newtable, cache) = cache
```

Let me know if you are interested, it should be a good exercise to keep practicing the GitHub PR model.

**Comment by ceferisbarov** [comment]
@juliohm Yes, absolutely. Thanks for letting me know.
