### ISSUE TITLE
Levels

### ISSUE THREAD

**Issue by JockLawrie** [JuliaML/TableTransforms.jl#70]
Hi there,

Is there appetite for a `SetLevels` transform that resets the levels of a column of scitype `Finite`?

Something along the lines of: `SetLevels(:mycol, levels)`

I often receive binary data with levels ["yes", "no"] and need to reorder them as ["no", "yes"], or simply recast them as [0, 1].

Another example is replacing alphabetical order with a more meaningful order.
E.g., ["large", "medium", "small"] changes to ["small", "medium", "large"]

**Comment by juliohm** [comment]
It would be nice to have a transform `Levels(:col1 => levels1, :col2 => levels2, ...)` that sets the levels of columns as you mentioned.

Can you help with a PR? :)

**Comment by juliohm** [comment]
@JockLawrie are you planning to work on this?

**Comment by Frank-III** [comment]
> @JockLawrie are you planning to work on this?

I would like to work on this one. I suppose the syntax to be `Levels(:cols1 => levels1, :col2 => level2; ordered = [:cols1, :cols3])` with the `order` keyword param to indicate the column we would like to set order to be true is ok?

**Comment by juliohm** [comment]
@Frank-III thank you for considering the contribution. Yes, the syntax is great. I will assign you to the issue and we can review the PR moving forward.

I was thinking if maybe this transform could be renamed to `Categorical` but we can think about it later when the PR is ready.

**Comment by juliohm** [comment]
Fixed in master.
