### ISSUE TITLE
Reverting `Select` inside pipeline fails if columntypes differ

### ISSUE THREAD

**Issue by antholzer** [JuliaML/TableTransforms.jl#76]
For example in the following
```julia
df = (; a=rand(Float32, 2), b=rand(2))
p = Select(:b) → MinMax()
newtable, cache = apply(p, df)
revert(p, newtable, cache)
```
the column a gets converted into a `Float64` vector
If one uses the following table `df = (; a=[rand(3), rand(3)], b=rand(2))` the inversion fails since since it tries to convert `Vector{Float64}` to `Float64`.

Is this behavior intentional? 

Explicitly creating and `Any` vector should fix it i.e.
```
diff --git a/src/transforms/select.jl b/src/transforms/select.jl
index 5748372..09ae813 100644
--- a/src/transforms/select.jl
+++ b/src/transforms/select.jl
@@ -108,7 +108,7 @@ function revert(::Select, newtable, cache)
   # selected columns
   cols   = Tables.columns(newtable)
   select = Tables.columnnames(cols)
-  scols  = [Tables.getcolumn(cols, name) for name in select]
+  scols  = Any[Tables.getcolumn(cols, name) for name in select]
 
   # rejected columns
   reject, rcols, sperm, rinds = cache
```

Shall I open a pull request for this fix?

**Comment by juliohm** [comment]
Thank you for reporting the bug @antholzer , we should definitely fix it. I wonder if adding `Any` is the right solution though. I don't have time to look into the code right now, but do you mean that the result of Select would always lead to `Any` columns in that case? Do we have an alternative solution?

**Comment by eliascarv** [comment]
The error is not in `Select` but in `Scale`. It is providing the column type to Float64 in its operations.

**Comment by juliohm** [comment]
Good catch @eliascarv , would you like to propose a fix? I am super busy here...

**Comment by antholzer** [comment]
Actually bot have an error with type conversion.
```
df = (; a=rand(Float32, 2), b=rand(2))
p=Select(:b) → DropMissing()
newtable, cache = apply(p, df)
revert(p, newtable, cache)
```
output:
```
# master
(a = [0.5341609716415405, 0.6113829612731934], b = [0.6949850019609314, 0.4067167096075357])
# with `Any`
(a = Float32[0.534161, 0.61138296], b = [0.6949850019609314, 0.4067167096075357])
```

`Any` is for the vector of all the columns i.e. the individual columns are still their respective types.

We should also get a concrete types for this vector in (line 123 in select.jl): `𝒯 = (; zip(anames, acols)...)`

The problem is that the vector that should hold the columns only gets initialized using the selected columns but later we `insert!` the rejected columns into it which causes the problem.
