### ISSUE TITLE
Improve IO methods of all transforms

### ISSUE THREAD

**Issue by juliohm** [JuliaML/TableTransforms.jl#85]
Currently we do not provide Base.show methods for the transforms and their output is quite difficult to digest. We could use some fancy unicode to display the transforms and pipelines to end users.

**Comment by eliascarv** [comment]
List of tranforms to inprove I/O:
[ ] Select
[ ] Reject
[ ] Rename
[ ] StdNames
[ ] Sort
[ ] Sample
[ ] Filter
[ ] DropMissing
[ ] Replace
[ ] Coalesce
[ ] Coerce
[ ] Levels
[ ] OneHot
[ ] RowTable
[ ] ColTable
[ ] Identity
[ ] Center
[ ] Scale
[ ] MinMax
[ ] Interquartile
[ ] ZScore
[ ] Quantile
[ ] Functional
[ ] Levels
[ ] Sort
[ ] EigenAnalysis
[ ] PCA
[ ] DRS
[ ] SDS
[ ] Sequential
[ ] Parallel

**Comment by juliohm** [comment]
Perhaps we can leverage the abstract Transform parent type to write a single show method for most transforms. This method could make use of fieldnames, and other Base functions to format and print the fields of the structs. In special cases, we could then write special methods for specific transforms like Sequential and Parallel to use some unicode with arrows.

**Comment by juliohm** [comment]
I think we can close this issue now that the fallback is in place? We can open specific issues if necessary to improve specific transforms?

**Comment by eliascarv** [comment]
I agree
